# SPDX-FileCopyrightText: Copyright (C) 2025 Fabr√≠cio Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: any-sonar
'on':
  push:
    branches:
      - main
      - master
permissions:
  contents: read
jobs:
  any-sonar:
    uses: fabriciofx/github-workflows/.github/workflows/any-sonar-template.yml@main
    with:
      working-directory: "."
      sonar_organization: "fabriciofx"
      sonar_project_key: "fabriciofx_github-workflows"
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      sr_token: ${{ secrets.SONAR_TOKEN }}
