# SPDX-FileCopyrightText: Copyright (C) 2025 Fabr√≠cio Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: any-sonar-test
'on':
  push:
    branches:
      - main
      - master
permissions:
  contents: read
jobs:
  any-sonar-test:
    uses: fabriciofx/github-workflows/.github/workflows/any-sonar-template.yml@main
    with:
      working-directory: "."
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      sr_token: ${{ secrets.SONAR_TOKEN }}
      sr_organization: ${{ secrets.SONAR_ORGANIZATION }}
      sr_project_key: ${{ secrets.SONAR_PROJECT_KEY }}
