# SPDX-FileCopyrightText: Copyright (C) 2025-2026 FabrÃ­cio Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: any-sonar-template
'on':
  workflow_call:
    inputs:
      working-directory:
        description: "Set the working directory"
        required: false
        default: "."
        type: string
      sonar_host_url:
        description: "Sonar host url"
        required: false
        default: "https://sonarcloud.io"
        type: string
    secrets:
      gh_token:
        description: "GitHub Token"
        required: true
      sr_token:
        description: "Sonar Token"
        required: true
      sr_organization:
        description: "Sonar organization (login)"
        required: true
      sr_project_key:
        description: "Sonar project key"
        required: true
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  any-sonar-template:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Create Sonar properties file
        working-directory: ${{ inputs.working-directory }}
        run: |
          cat > sonar-project.properties <<EOF
          sonar.organization=${{ secrets.sr_organization }}
          sonar.projectKey=${{ secrets.sr_project_key }}
          sonar.sources=.
          sonar.inclusions=**
          sonar.exclusions=node_modules/**,dist/**,build/**
          sonar.sourceEncoding=UTF-8
          sonar.issuesReport.console.enable=true
          sonar.c.file.suffixes=-
          sonar.cpp.file.suffixes=-
          sonar.objc.file.suffixes=-
          EOF
      - name: Run Sonar
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.sr_token }}
