# SPDX-FileCopyrightText: Copyright (C) 2025 Fabr√≠cio Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: bash-format-template
'on':
  workflow_call:
    inputs:
      working-directory:
        description: "Set the working directory"
        required: false
        default: "."
        type: string
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  bash-format-template:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup Python SDK
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Install bashate
        working-directory: ${{ inputs.working-directory }}
        run: pip install bashate
      - name: Check bash format
        working-directory: ${{ inputs.working-directory }}
        run: |
          readarray -t files < <(find . -name "*.sh")
          [[ ${#files[@]} -eq 0 ]] && {
            echo "No '*.sh'. files found.";
            exit 0;
          }
          bashate -i E006,E003 "${files[@]}"
