# SPDX-FileCopyrightText: Copyright (C) 2025 Fabr√≠cio Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: c-cpp-build-template
'on':
  workflow_call:
    inputs:
      working-directory:
        description: "Set the working directory"
        required: false
        default: "."
        type: string
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  c-cpp-linux-build-template:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Configure APT cache
        uses: actions/cache@v5
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/apt-packages.txt') }}
          restore-keys: ${{ runner.os }}-apt-
      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: |
          if [[ -s apt-packages.txt ]]; then
            sudo apt-get update
            xargs sudo apt-get install -y \
              --no-install-recommends < apt-packages.txt
          fi
      - name: Configure and build
        working-directory: ${{ inputs.working-directory }}
        run: |
          [[ -x ./autogen.sh ]] && ./autogen.sh
          [[ -x ./configure ]] && ./configure
          [[ -s Makefile ]] || {
            echo "I couldn't find an autogen.sh, configure, or Makefile."
            echo "Please check your files."
            exit 1
          }
          make
      - name: Get properties from configure.ac
        working-directory: ${{ inputs.working-directory }}
        id: props
        run: |
          name="$(sed -n 's/AC_INIT(\[\([^]]*\)\],.*/\1/p' configure.ac)"
          echo "name=${name}" >> "${GITHUB_OUTPUT}"
          version="$(sed -n 's/AC_INIT(\[[^]]*\], \[\([^]]*\)\], \[[^]]*\])/\1/p' configure.ac)"
          echo "version=${version}" >> "${GITHUB_OUTPUT}"
      - name: Create source package
        working-directory: ${{ inputs.working-directory }}
        run: |
          make dist
      - name: Create Linux binary package
        working-directory: ${{ inputs.working-directory }}
        run: |
          make binary-dist
      - name: Prepare packages to distribution
        working-directory: ${{ inputs.working-directory }}
        env:
          NAME: ${{ steps.props.outputs.name }}
          VERSION: ${{ steps.props.outputs.version }}
        run: |
          # Sanitize variables for security purposes
          safe_name="$(echo "${NAME}" | tr -cd '[:alnum:]._-' )"
          safe_version="$(echo "${VERSION}" | tr -cd '[:alnum:]._-' )"

          # Check if variables are empty
          [[ -z "$safe_name" ]] && { echo "Invalid name"; exit 1; }
          [[ -z "$safe_version" ]] && { echo "Invalid version"; exit 1; }

          # Check if files exists
          src="${safe_name}-${safe_version}.tar.gz"
          bin="${safe_name}-${safe_version}-bin.tar.gz"
          [[ -f "$src" ]] || { echo "File '${src}' not found"; exit 1; }
          [[ -f "$bin" ]] || { echo "File '${bin}' not found"; exit 1; }

          # Move files
          mkdir -p dist
          mv "${src}" dist/
          mv "${bin}" "dist/${safe_name}-${safe_version}-linux.tar.gz"
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v6
        with:
          name: linux-dist
          path: "${{ inputs.working-directory }}/dist/*.tar.gz"
  c-cpp-macos-build-template:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: |
          if [[ -s brew-packages.txt ]]; then
            brew update
            xargs brew install < brew-packages.txt
          fi
      - name: Configure and build
        working-directory: ${{ inputs.working-directory }}
        run: |
          [[ -x ./autogen.sh ]] && ./autogen.sh
          [[ -x ./configure ]] && ./configure
          [[ -s Makefile ]] || {
            echo "I couldn't find an autogen.sh, configure, or Makefile."
            echo "Please check your files."
            exit 1
          }
          make
      - name: Get properties from configure.ac
        working-directory: ${{ inputs.working-directory }}
        id: props
        run: |
          name="$(sed -n 's/AC_INIT(\[\([^]]*\)\],.*/\1/p' configure.ac)"
          echo "name=${name}" >> "${GITHUB_OUTPUT}"
          version="$(sed -n 's/AC_INIT(\[[^]]*\], \[\([^]]*\)\], \[[^]]*\])/\1/p' configure.ac)"
          echo "version=${version}" >> "${GITHUB_OUTPUT}"
      - name: Create macOS binary package
        working-directory: ${{ inputs.working-directory }}
        run: |
          make binary-dist
      - name: Prepare package to distribution
        working-directory: ${{ inputs.working-directory }}
        env:
          NAME: ${{ steps.props.outputs.name }}
          VERSION: ${{ steps.props.outputs.version }}
        run: |
          # Sanitize variables for security purposes
          safe_name="$(echo "${NAME}" | tr -cd '[:alnum:]._-' )"
          safe_version="$(echo "${VERSION}" | tr -cd '[:alnum:]._-' )"

          # Check if variables are empty
          [[ -z "$safe_name" ]] && { echo "Invalid name"; exit 1; }
          [[ -z "$safe_version" ]] && { echo "Invalid version"; exit 1; }

          # Check if file exist
          bin="${safe_name}-${safe_version}-bin.tar.gz"
          [[ -f "$bin" ]] || { echo "File '${bin}' not found"; exit 1; }

          # Move file
          mkdir -p dist
          mv "${bin}" "dist/${safe_name}-${safe_version}-macos.tar.gz"
      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v6
        with:
          name: macos-dist
          path: "${{ inputs.working-directory }}/dist/*.tar.gz"
