# SPDX-FileCopyrightText: Copyright (C) 2025 Fabr√≠cio Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: c-cpp-build-template
'on':
  workflow_call:
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  c-cpp-linux-build-template:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Check if code exists
        id: check
        uses: thebinaryfelix/check-file-existence-action@436223737a098725b8d10ab1950a03efba5e6fc6
        with:
          files: 'autogen.sh, configure, Makefile'
      - name: Configure APT cache
        if: steps.check.outputs.exists == 'true'
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/apt-packages.txt') }}
          restore-keys: ${{ runner.os }}-apt-
      - name: Install dependencies
        run: |
          if [[ -s apt-packages.txt ]]; then
            sudo apt-get update
            xargs sudo apt-get install -y \
              --no-install-recommends < apt-packages.txt
          fi
      - name: Configure and build
        run: |
          [[ -x ./autogen.sh ]] && ./autogen.sh
          [[ -x ./configure ]] && ./configure
          [[ -s Makefile ]] || {
            echo "I couldn't find an autogen.sh, configure, or Makefile."
            echo "Please check your files."
            exit 1
          }
          make
      - name: Get properties from configure.ac
        id: props
        run: |
          name="$(sed -n 's/AC_INIT(\[\([^]]*\)\],.*/\1/p' configure.ac)"
          echo "name=${name}" >> "${GITHUB_OUTPUT}"
          version="$(sed -n 's/AC_INIT(\[[^]]*\], \[\([^]]*\)\], \[[^]]*\])/\1/p' configure.ac)"
          echo "version=${version}" >> "${GITHUB_OUTPUT}"
      - name: Create source package
        run: |
          make dist
      - name: Create Linux binary package
        run: |
          make binary-dist
      - name: Prepare packages to distribution
        run: |
          # Sanitize variables for security purposes
          safe_name="$(echo "${{ steps.props.outputs.name }}" | tr -cd '[:alnum:]._-' )"
          safe_version="$(echo "${{ steps.props.outputs.version }}" | tr -cd '[:alnum:]._-' )"

          # Check if variables are empty
          [[ -z "$safe_name" ]] && { echo "Invalid name"; exit 1; }
          [[ -z "$safe_version" ]] && { echo "Invalid version"; exit 1; }

          # Check if files exists
          src="${safe_name}-${safe_version}.tar.gz"
          bin="${safe_name}-${safe_version}-bin.tar.gz"
          [[ -f "$src" ]] || { echo "File '${src}' not found"; exit 1; }
          [[ -f "$bin" ]] || { echo "File '${bin}' not found"; exit 1; }

          # Move files
          mkdir -p dist
          mv "${src}" dist/
          mv "${bin}" "dist/${safe_name}-${safe_version}-linux.tar.gz"
  c-cpp-macos-build-template:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Check if code exists
        id: check
        uses: thebinaryfelix/check-file-existence-action@436223737a098725b8d10ab1950a03efba5e6fc6
        with:
          files: 'autogen.sh, configure, Makefile'
      - name: Install dependencies
        if: steps.check.outputs.exists == 'true'
        run: |
          if [[ -s brew-packages.txt ]]; then
            brew update
            xargs brew install < brew-packages.txt
          fi
      - name: Configure and build
        run: |
          [[ -x ./autogen.sh ]] && ./autogen.sh
          [[ -x ./configure ]] && ./configure
          [[ -s Makefile ]] || {
            echo "I couldn't find an autogen.sh, configure, or Makefile."
            echo "Please check your files."
            exit 1
          }
          make
      - name: Get properties from configure.ac
        id: props
        run: |
          name="$(sed -n 's/AC_INIT(\[\([^]]*\)\],.*/\1/p' configure.ac)"
          echo "name=${name}" >> "${GITHUB_OUTPUT}"
          version="$(sed -n 's/AC_INIT(\[[^]]*\], \[\([^]]*\)\], \[[^]]*\])/\1/p' configure.ac)"
          echo "version=${version}" >> "${GITHUB_OUTPUT}"
      - name: Create macOS binary package
        run: |
          make binary-dist
      - name: Prepare package to distribution
        run: |
          # Sanitize variables for security purposes
          safe_name="$(echo "${{ steps.props.outputs.name }}" | tr -cd '[:alnum:]._-' )"
          safe_version="$(echo "${{ steps.props.outputs.version }}" | tr -cd '[:alnum:]._-' )"

          # Check if variables are empty
          [[ -z "$safe_name" ]] && { echo "Invalid name"; exit 1; }
          [[ -z "$safe_version" ]] && { echo "Invalid version"; exit 1; }

          # Check if file exist
          bin="${safe_name}-${safe_version}-bin.tar.gz"
          [[ -f "$bin" ]] || { echo "File '${bin}' not found"; exit 1; }

          # Move file
          mkdir -p dist
          mv "${bin}" dist/"${safe_name}-${safe_version}-macos.tar.gz"
  c-cpp-windows-build-template:
    runs-on: windows-2025
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Check if code exists
        id: check
        uses: thebinaryfelix/check-file-existence-action@436223737a098725b8d10ab1950a03efba5e6fc6
        with:
          files: 'autogen.sh, configure, Makefile'
      - name: Install and setup MSYS2 with MinGW64
        if: steps.check.outputs.exists == 'true'
        uses: msys2/setup-msys2@ee87529e22c13ef957bcd5ef65c3ca2d61025d19
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel
            autoconf
            automake
            libtool
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-make
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-libpcap
            mingw-w64-x86_64-tcl
      - name: Configure and build
        shell: msys2 {0}
        run: |
          [[ -x ./autogen.sh ]] && ./autogen.sh
          [[ -x ./configure ]] && ./configure --host=x86_64-w64-mingw64
          [[ -s Makefile ]] || {
            echo "I couldn't find an autogen.sh, configure, or Makefile."
            echo "Please check your files."
            exit 1
          }
          make
      - name: Get properties from configure.ac
        id: props
        run: |
          name="$(sed -n 's/AC_INIT(\[\([^]]*\)\],.*/\1/p' configure.ac)"
          echo "name=${name}" >> "${GITHUB_OUTPUT}"
          version="$(sed -n 's/AC_INIT(\[[^]]*\], \[\([^]]*\)\], \[[^]]*\])/\1/p' configure.ac)"
          echo "version=${version}" >> "${GITHUB_OUTPUT}"
      - name: Create source package
        run: |
          make dist
      - name: Create Windows binary package
        run: |
          make binary-dist
      - name: Prepare packages to distribution
        run: |
          md dist
          move "${{ steps.props.outputs.name }}-${{ steps.props.outputs.version }}-bin.zip" ^
            "dist/${{ steps.props.outputs.name }}-${{ steps.props.outputs.version }}-windows.zip"
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist
          path: dist/*.zip
