# SPDX-FileCopyrightText: Copyright (C) 2025 FabrÃ­cio Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: check-semver-tag-template
'on':
  workflow_call:
    inputs:
      working-directory:
        description: "Set the working directory"
        required: false
        default: "."
        type: string
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  check-semver-tag-template:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Check semantic version tag name
        id: workflows
        run: |
          if [[ "${GITHUB_REF_NAME}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "cancel=false" >> "${GITHUB_OUTPUT}"
          else
            echo "Tag '${GITHUB_REF_NAME}' has an invalid semver name format."
            echo "Please, use a valid format: ^[0-9]+\.[0-9]+\.[0-9]+$"
            echo "For more information, visit the website https://semver.org/"
            echo "cancel=true" >> "${GITHUB_OUTPUT}"
          fi
      - name: Cancel all active workflows
        if: steps.workflows.outputs.cancel == 'true'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel
