# SPDX-FileCopyrightText: Copyright (C) 2025-2026 Fabr√≠cio Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: java-sonatype-release-test
'on':
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
permissions:
  contents: read
jobs:
  java-sonatype-release-test:
    uses: fabriciofx/github-workflows/.github/workflows/java-sonatype-release-template.yml@main
    with:
      working-directory: "java/test"
    secrets:
      release_keyname: ${{ secrets.GPG_KEYNAME }}
      release_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      release_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      release_username: ${{ secrets.OSSRH_USERNAME }}
      release_password: ${{ secrets.OSSRH_PASSWORD }}
