# SPDX-FileCopyrightText: Copyright (C) 2025 Fabr√≠cio Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: java-build-template
'on':
  workflow_call:
    inputs:
      working-directory:
        description: "Set the working directory"
        required: false
        default: "."
        type: string
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  java-linux-build-template:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        java: [21]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup Java SDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Configure Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - name: Build Maven project
        working-directory: ${{ inputs.working-directory }}
        run: |
          [[ -x "mvnw" ]] && mvn="./mvnw" || mvn="mvn"
          args=(--errors --batch-mode install)
          profile=$(grep -q "<id>qulice</id>" pom.xml && echo "-Pqulice")
          [[ -n "${profile}" ]] && args+=("${profile}")
          ${mvn} "${args[@]}"
  java-macos-build-template:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-15]
        java: [21]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup Java SDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Configure Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ github.job }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ github.job }}-
      - name: Build Maven project
        working-directory: ${{ inputs.working-directory }}
        run: |
          [[ -x "mvnw" ]] && mvn="./mvnw" || mvn="mvn"
          args=(--errors --batch-mode install)
          profile=$(grep -q "<id>qulice</id>" pom.xml && echo "-Pqulice")
          [[ -n "${profile}" ]] && args+=("${profile}")
          ${mvn} "${args[@]}"
  java-windows-build-template:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, windows-2025]
        java: [21]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup Java SDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Configure Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ github.job }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ github.job }}-
      - name: Build Maven project
        shell: cmd
        working-directory: ${{ inputs.working-directory }}
        run: |
          @echo off
          for /f "delims=" %%i in ('findstr "<id>qulice</id>" pom.xml') do set "Q=1"
          if exist "mvnw.cmd" (set "M=mvnw.cmd") else (set "M=mvn")
          %M% --errors --batch-mode install %Q:~-2,-1%-Pqulice
