# SPDX-FileCopyrightText: Copyright (C) 2025 FabrÃ­cio Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: java-sonar-template
'on':
  workflow_call:
    inputs:
      working-directory:
        description: "Set the working directory"
        required: false
        default: "."
        type: string
      sonar_host_url:
        description: "Sonar host url"
        required: false
        default: "https://sonarcloud.io"
        type: string
    secrets:
      gh_token:
        description: "GitHub Token"
        required: true
      sr_token:
        description: "Sonar Token"
        required: true
      sr_organization:
        description: "Sonar organization (login)"
        required: true
      sr_project_key:
        description: "Sonar project key"
        required: true
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  java-sonar-template:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup Java SDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Configure Maven cache
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ubuntu-jdk-17-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-jdk-17-maven-
      - name: Build Maven project
        working-directory: ${{ inputs.working-directory }}
        run: |
          [[ -x "mvnw" ]] && mvn="./mvnw" || mvn="mvn"
          profile=$(${mvn} help:all-profiles | grep -q "qulice" && echo "-Pqulice")
          ${mvn} --errors --batch-mode install "${profile}"
      - name: Create Sonar properties file
        working-directory: ${{ inputs.working-directory }}
        run: |
          cat > sonar-project.properties <<EOF
          sonar.organization=${{ secrets.sr_organization }}
          sonar.projectKey=${{ secrets.sr_project_key }}
          sonar.sources=.
          sonar.java.binaries=.
          sonar.host.url=${{ inputs.sonar_host_url }}
          sonar.inclusions=**
          sonar.exclusions=node_modules/**,dist/**,build/**
          sonar.sourceEncoding=UTF-8
          sonar.issuesReport.console.enable=true
          sonar.c.file.suffixes=-
          sonar.cpp.file.suffixes=-
          sonar.objc.file.suffixes=-
          EOF
      - name: Run Sonar
        working-directory: ${{ inputs.working-directory }}
        env:
          SONAR_TOKEN: ${{ secrets.sr_token }}
        run: |
          [[ -x "mvnw" ]] && mvn="./mvnw" || mvn="mvn"
          profile=$(${mvn} help:all-profiles | grep -q "sonar" && echo "-Psonar")
          [[ -z "${profile}" ]] || \
            { echo "Error: 'sonar' profile not found in pom.xml or parent"; exit 1; }
          ${mvn} --errors --batch-mode -Psonar
