# SPDX-FileCopyrightText: Copyright (C) 2025-2026 Fabr√≠cio Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: java-infer-test
'on':
  push:
    branches:
      - main
      - master
permissions:
  contents: read
jobs:
  java-infer-test:
    uses: fabriciofx/github-workflows/.github/workflows/java-infer-template.yml@main
    with:
      working-directory: "java/test"
