# SPDX-FileCopyrightText: Copyright (C) 2025-2026 Fabr√≠cio Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: latex-build-template
'on':
  workflow_call:
    inputs:
      working-directory:
        description: "Set the working directory"
        required: false
        default: "."
        type: string
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  latex-build-template:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/xu-cheng/texlive-debian:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Compile LaTeX document
        working-directory: ${{ inputs.working-directory }}
        run: |
          [[ -s Makefile ]] || {
            echo "Makefile file not found. Please, check your project.";
            exit 1;
          }
          make
      - name: Upload documents
        uses: actions/upload-artifact@v7
        env:
          WORKING_DIR: ${{ inputs.working-directory }}
        with:
          name: document
          path: "${WORKING_DIR}/*.pdf"
