# SPDX-FileCopyrightText: Copyright (C) 2025 Fabr√≠cio Barros Cabral
# SPDX-License-Identifier: MIT
---
name: loc-badge
'on':
  push:
    branches:
      - main
      - master
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
concurrency:
  group: loc-badge-${{ github.ref }}
  cancel-in-progress: true
jobs:
  loc-badge:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Build a LOC badge
        uses: shadowmoose/GHA-LoC-Badge@ccb1053d8fd9015ed6ab0753e85b63b1e9ec0650
        with:
          debug: true
          directory: .
          badge: target/loc-badge.svg
      - name: Release it into gh-pages
        # yamllint disable-line rule:line-length
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8
        with:
          branch: gh-pages
          folder: target
          clean: false
        if: github.ref == 'refs/heads/main'
