# SPDX-FileCopyrightText: Copyright (C) 2025 Fabr√≠cio Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: python-format-template
'on':
  workflow_call:
    inputs:
      working-directory:
        description: "Set the working directory"
        required: false
        default: "."
        type: string
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  python-format-template:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install venv and dependencies
        working-directory: ${{ inputs.working-directory }}
        run: |
          if [[ -s Makefile ]]; then
            make install
          else
            python -m venv .venv
            . ./.venv/bin/activate
            pip install -r requirements.txt
          fi
      - name: Download and install ruff
        working-directory: ${{ inputs.working-directory }}
        run: pip install ruff
      - name: Check format
        working-directory: ${{ inputs.working-directory }}
        run: ruff format --check
