# SPDX-FileCopyrightText: Copyright (C) 2025 Fabr√≠cio Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: python-release-template
'on':
  workflow_call:
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  id-token: write
  contents: read
jobs:
  python-release-template:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Check if code exists
        id: check
        uses: thebinaryfelix/check-file-existence-action@436223737a098725b8d10ab1950a03efba5e6fc6
        with:
          files: '**/*.py'
      - name: Set up Python
        if: steps.check.outputs.exists == 'true'
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install build tool
        run: pip install build
      - name: Build package
        run: python -m build
      - name: Release to PyPI
        uses: pypa/gh-action-pypi-publish@ab69e431e9c9f48a3310be0a56527c679f56e04d
        with:
          verbose: true
